# Generated by Django 4.2.7 on 2025-11-20 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who finally approved this request",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
