# Generated by Django 4.2.7 on 2025-11-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0002_purchaserequest_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="proforma_extracted_data",
            field=models.JSONField(
                blank=True, help_text="Extracted data from proforma invoice", null=True
            ),
        ),
    ]
